# Use the official Node.js v18.4.0 image as the base
FROM node:18.4.0

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose port 3000 for the application to listen on
EXPOSE 8080

# Start the Node.js application
ENTRYPOINT [ "npm", "start" ]
CMD [ "--port", "8080" ]

